export const CHANGE_NOTES_RANGE = "CHANGE_NOTES_RANGE";
export const SET_BORDERS_OF_RANGE = "SET_BORDERS_OF_RANGE";

export const SET_ACTIVE_TYPE_OF_INTERVAL = "SET_ACTIVE_TYPE_OF_INTERVAL";
export const SET_NEW_INTERVAL = "SET_NEW_INTERVAL";
export const SET_SEQUENCE_OF_NOTES = "SET_SEQUENCE_OF_NOTES";

// export const SHOW_THE_CORRECT_INTERVAL = "SHOW_THE_CORRECT_INTERVAL";
// export const INCREMENT_RIGHT_ANSWERS = "INCREMENT_RIGHT_ANSWERS";
// export const INCREMENT_AMOUNT_OF_ANSWERS = "INCREMENT_AMOUNT_OF_ANSWERS";
