export const MENU_ACTION = "MENU_ACTION";
export const NEED_TO_WRITE_NOTE = "NEED_TO_WRITE_NOTE";
export const WRITE_PLAY_NOTE = "WRITE_PLAY_NOTE";
export const INIT_DICTATION = "INIT_DICTATION";
export const SET_MODE = "SET_MODE";

export const UPDATE_PIANO_KEYS = "UPDATE_PIANO_KEYS";
export const SET_BORDERS_OF_RANGE = "SET_BORDERS_OF_RANGE";
export const SHOW_NOTES_ON_THE_PIANO = "SHOW_NOTES_ON_THE_PIANO";
export const TURN_OFF_VISUALIZATION = "TURN_OFF_VISUALIZATION";

export const SET_ACTIVE_NOTE = "SET_ACTIVE_NOTE";

export const SET_ACTIVE_TYPE_OF_INTERVAL = "SET_ACTIVE_TYPE_OF_INTERVAL";
export const SET_NEW_INTERVAL = "SET_NEW_INTERVAL";
export const INTERVALS_SETTINGS_ACTION = "INTERVALS_SETTINGS_ACTION";
export const INVERSE_CHOSEN_INTERVAL = "INVERSE_CHOSEN_INTERVAL";
export const GET_ANSWER_INTERVAL = "GET_ANSWER_INTERVAL";
export const GET_NEXT_INTERVAL = "GET_NEXT_INTERVAL";

export const SHOW_THE_CORRECT_INTERVAL = "SHOW_THE_CORRECT_INTERVAL";
export const INCREMENT_RIGHT_ANSWERS = "INCREMENT_RIGHT_ANSWERS";
export const INCREMENT_AMOUNT_OF_ANSWERS = "INCREMENT_AMOUNT_OF_ANSWERS";
export const NEXT_BUTTON_CLICK = "NEXT_BUTTON_CLICK";
export const STATISTICS_CLEARING = "STATISTICS_CLEARING";
export const STATISTICS_HIDE_ANSWER = "STATISTICS_HIDE_ANSWER";

export const GET_NEW_MELODY = "GET_NEW_MELODY";
export const CHANGE_MODE = "CHANGE_MODE";
export const ADD_NOTE_TO_ANSWER_ARRAY = "ADD_NOTE_TO_ANSWER_ARRAY";
export const POP_LAST_ELEM_FROM_ANSWER_ARRAY =
  "POP_LAST_ELEM_FROM_ANSWER_ARRAY";
export const WRITE_ANSWERS = "WRITE_ANSWERS";
export const CLEAR_WRITTEN_MELODY = "CLEAR_WRITTEN_MELODY";
export const CHANGE_SETTINGS = "CHANGE_SETTINGS";
