export const CHANGE_NOTES_RANGE = "CHANGE_NOTES_RANGE";
export const SET_BORDERS_OF_RANGE = "SET_BORDERS_OF_RANGE";

export const SET_ACTIVE_TYPE_OF_INTERVAL = "SET_ACTIVE_TYPE_OF_INTERVAL";
export const SET_NEW_INTERVAL = "SET_NEW_INTERVAL";
export const SETTINGS_CLICK = "SETTINGS_CLICK";
export const INVERSE_CHOSEN_INTERVAL = "INVERSE_CHOSEN_INTERVAL";
export const GET_ANSWER_INTERVAL = "GET_ANSWER_INTERVAL";
export const GET_NEXT_INTERVAL = "GET_NEXT_INTERVAL";

export const SHOW_THE_CORRECT_INTERVAL = "SHOW_THE_CORRECT_INTERVAL";
export const INCREMENT_RIGHT_ANSWERS = "INCREMENT_RIGHT_ANSWERS";
export const INCREMENT_AMOUNT_OF_ANSWERS = "INCREMENT_AMOUNT_OF_ANSWERS";
export const NEXT_BUTTON_CLICK = "NEXT_BUTTON_CLICK";
